version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "secrets"
enabled = true
dependency_file_paths = [
"testcontent/**"
]
[[analyzers]]
name = "test-coverage"
enabled = true
dependency_file_paths = [
"testcontent/**"
]
