workflows:
  my-workflow:
    name: codemagic
    labels:
      - QA
      - ${TENANT_NAME}
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        PUBLIC_ENV_VAR: "value here"
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    artifacts:
      - build/**/outputs/bundle/**/*.aab
