on:
  push:
    branches:
      - main
      - allurectl
  pull_request:
    branches:
      - main
      - allurectl

permissions: read-all

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - uses: allure-framework/setup-allurectl@v1
        with: 
          allure-endpoint: https://demo.testops.cloud
          allure-token: ${{ secret.ALLURE_TOKEN }}
          allure-project-id: 1
      - run: allurectl watch -- ./gradlew clean test
        env: 
          ALLURE_RESULTS: build/allure-results
