version: 1.0.0.{build}
branches:
  only:
  - main
  - appveyor
shallow_clone: true
build:
  project: SPORE™ Creatures extract.sln
  verbosity: detailed
test:
  categories:
    only:
    - '**\SPORE-Creatures-extract.exe'
