name: CodecovName
on:
  push:
    branches:
      - main
      - CodecovBranch
    tags:
      - "!*" # Do not execute on tags
  pull_request:
    branches:
      - main
      - CodecovBranch

jobs:
  coverage:
    name: codecov
    runs-on: windows-latest
    steps:
      - name: Run Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
