name: Codecov
on:
  push:
    branches:
      - main
      - CodecovBranch
    tags:
      - "!*" # Do not execute on tags
  pull_request:
    branches:
      - main
      - CodecovBranch

jobs:
  codecov:
    name: codecov
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
