name: CodecovName
on:
  push:
    branches:
      - main
      - CodecovBranch
  pull_request:
    branches:
      - main
      - CodecovBranch
jobs:
  coverage:
    runs-on: windows-latest
    steps:
      - name: Run Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
