name: Codecov
on:
  push:
    branches:
      - main
      - CodecovBranch
  pull_request:
    branches:
      - main
      - CodecovBranch

permissions: read-all

jobs:
  coverage:
    name: codecov
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
