name: DeepSource Action
on:
  push:
    branches:
    - main
    - deepsource
  pull_request:
    branches:
    - main
    - deepsource

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: python
          coverage-file: coverage.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
